server.port=8080
spring.application.name=auth-service

spring.cloud.openfeign.client.config.default.connect-timeout=3000
spring.cloud.openfeign.client.config.default.read-timeout=3000
spring.cloud.openfeign.circuitbreaker.enabled=true

logging.level.org.springframework.cloud.openfeign=DEBUG
logging.level.io.github.resilience4j.circuitbreaker=DEBUG
